main: fr.tonychouteau.murder.bukkit.MurderPlugin
name: MurderPlugin
version: 0.0.9
description: Murder
author: Tony Chouteau
api-version: 1.13
commands:
  murder:
    description: Commandes du plugin murder
    usage: /murder help | spawnpoint | start | stop
    permission: permission.murder
    aliases:
      - muder help
      - murder start
      - murder stop
      - murder spawnpoint
  m:
    description: Commandes du plugin murder
    usage: /m help | spawnpoint | start | stop
    permission: permission.murder
    aliases:
      - m help
      - m start
      - m stop
      - m sp